import type {
  VoiceAgent,
  CallLog,
  Campaign,
  Contact,
  PhoneNumber,
  Transaction,
  ClientAccount,
  Plan,
  ProviderConfig,
  SupportTicket,
} from "./types";

export const seedAgents: VoiceAgent[] = [
  {
    id: "agent_riya",
    name: "Riya — Sales Caller",
    useCase: "Sales & Lead Qualification",
    description: "Calls new website leads within 5 minutes, qualifies budget & books demos.",
    status: "active",
    language: "hi-EN",
    voice: "priya",
    model: "claude-sonnet-5",
    greeting: "Namaste! Main Riya bol rahi hoon SharmaTech se. Aapne humari website par enquiry ki thi — kya abhi 2 minute baat kar sakte hain?",
    systemPrompt:
      "You are Riya, a friendly sales agent for SharmaTech Solutions. Qualify leads on requirement, budget and timeline. Switch naturally between Hindi and English. If qualified, offer demo slots for tomorrow 11 AM or 4 PM and confirm on WhatsApp.",
    temperature: 0.7,
    speakingRate: 1,
    interruptible: true,
    maxCallMinutes: 6,
    silenceTimeoutSec: 8,
    knowledgeFaqs: [
      { q: "What is the pricing?", a: "Plans start at ₹4,999/month for the basic CRM package." },
      { q: "Do you offer a free trial?", a: "Yes, a 14-day free trial with full features." },
    ],
    webhookUrl: "https://hooks.sharmatech.in/leads",
    whatsappFollowUp: true,
    calendarBooking: true,
    crmPush: true,
    totalCalls: 1842,
    avgDurationSec: 148,
    successRate: 68,
    createdAt: "2026-04-12T09:30:00Z",
  },
  {
    id: "agent_kabir",
    name: "Kabir — EMI Reminder",
    useCase: "EMI & Payment Reminders",
    description: "Polite RBI-compliant EMI due reminders with WhatsApp payment links.",
    status: "active",
    language: "hi-IN",
    voice: "aarav",
    model: "claude-haiku-4-5",
    greeting: "Namaskar, main Kabir bol raha hoon FinServe ki taraf se. Yeh aapke loan EMI ke baare mein ek reminder call hai.",
    systemPrompt:
      "You are Kabir, a payment reminder agent for FinServe NBFC. Follow RBI fair-practice code strictly: courteous tone, no threats, call window 8 AM – 7 PM. Confirm identity, remind about the due amount, offer a WhatsApp payment link, and record any promise-to-pay date.",
    temperature: 0.4,
    speakingRate: 0.95,
    interruptible: true,
    maxCallMinutes: 4,
    silenceTimeoutSec: 6,
    knowledgeFaqs: [{ q: "Late payment charges?", a: "2% per month on the overdue amount as per the loan agreement." }],
    webhookUrl: "https://api.finserve.in/webhooks/ptp",
    whatsappFollowUp: true,
    calendarBooking: false,
    crmPush: true,
    totalCalls: 5211,
    avgDurationSec: 92,
    successRate: 74,
    createdAt: "2026-03-02T11:00:00Z",
  },
  {
    id: "agent_asha",
    name: "Asha — Clinic Receptionist",
    useCase: "Appointment Booking",
    description: "24×7 inbound receptionist for Dr. Mehta's Dental Clinic, Pune.",
    status: "paused",
    language: "mr-IN",
    voice: "meera",
    model: "claude-sonnet-5",
    greeting: "Namaskar, Dr. Mehta Dental Clinic madhe aapale swagat aahe. Mi Asha boltey — appointment book karaychi aahe ka?",
    systemPrompt:
      "You are Asha, receptionist for Dr. Mehta's Dental Clinic in Pune. Book appointments in available slots (Mon–Sat, 10 AM – 8 PM), answer common questions about treatments and pricing, and send WhatsApp confirmations. Speak Marathi by default, switch to Hindi/English if the caller does.",
    temperature: 0.6,
    speakingRate: 1,
    interruptible: true,
    maxCallMinutes: 5,
    silenceTimeoutSec: 8,
    knowledgeFaqs: [
      { q: "Root canal cost?", a: "₹3,500 to ₹6,000 depending on the tooth." },
      { q: "Is teeth cleaning painful?", a: "No, it is a painless 30-minute procedure." },
    ],
    webhookUrl: "",
    whatsappFollowUp: true,
    calendarBooking: true,
    crmPush: false,
    totalCalls: 967,
    avgDurationSec: 121,
    successRate: 88,
    createdAt: "2026-05-20T15:45:00Z",
  },
];

export const seedCalls: CallLog[] = [
  {
    id: "call_9001",
    agentName: "Riya — Sales Caller",
    contactName: "Rahul Verma",
    phone: "+91 98201 44xxx",
    direction: "outbound",
    status: "completed",
    durationSec: 204,
    costInr: 15.3,
    sentiment: "positive",
    outcome: "Demo booked — Tue 11:00 AM",
    startedAt: "2026-07-07T10:42:00Z",
    transcript: [
      { speaker: "agent", text: "Namaste Rahul ji! Main Riya bol rahi hoon SharmaTech se. Aapne kal humari website par CRM ke liye enquiry ki thi." },
      { speaker: "user", text: "Haan haan, bataiye. Pricing kya hai aapki?" },
      { speaker: "agent", text: "Sure! Humara basic plan ₹4,999 per month se start hota hai. Aapki team mein kitne log hain?" },
      { speaker: "user", text: "Around 12 people in sales." },
      { speaker: "agent", text: "Perfect, 12 logon ke liye Growth plan best rahega. Kya main kal 11 baje ek quick demo schedule kar doon?" },
      { speaker: "user", text: "Theek hai, 11 baje chalega." },
      { speaker: "agent", text: "Great! Demo confirm ho gaya — details WhatsApp par bhej rahi hoon. Thank you Rahul ji!" },
    ],
  },
  {
    id: "call_9002",
    agentName: "Kabir — EMI Reminder",
    contactName: "Sunita Devi",
    phone: "+91 91556 78xxx",
    direction: "outbound",
    status: "completed",
    durationSec: 88,
    costInr: 6.6,
    sentiment: "neutral",
    outcome: "Promise to pay — 10 Jul",
    startedAt: "2026-07-07T09:15:00Z",
    transcript: [
      { speaker: "agent", text: "Namaskar, kya meri baat Sunita Devi ji se ho rahi hai?" },
      { speaker: "user", text: "Haan, boliye." },
      { speaker: "agent", text: "Main FinServe se Kabir bol raha hoon. Aapki ₹4,250 ki EMI 5 July ko due thi. Kya aap payment kar payengi?" },
      { speaker: "user", text: "Is hafte salary aayegi, 10 tarikh tak kar dungi." },
      { speaker: "agent", text: "Bilkul theek hai. Maine 10 July note kar liya hai aur payment link WhatsApp par bhej diya hai. Dhanyavaad!" },
    ],
  },
  {
    id: "call_9003",
    agentName: "Riya — Sales Caller",
    contactName: "Farhan Sheikh",
    phone: "+91 99304 12xxx",
    direction: "outbound",
    status: "no-answer",
    durationSec: 0,
    costInr: 0.5,
    sentiment: "neutral",
    outcome: "Retry scheduled +2h",
    startedAt: "2026-07-07T08:58:00Z",
    transcript: [],
  },
  {
    id: "call_9004",
    agentName: "Asha — Clinic Receptionist",
    contactName: "Pooja Kulkarni",
    phone: "+91 98600 33xxx",
    direction: "inbound",
    status: "completed",
    durationSec: 143,
    costInr: 10.7,
    sentiment: "positive",
    outcome: "Appointment — Sat 5:30 PM",
    startedAt: "2026-07-06T18:20:00Z",
    transcript: [
      { speaker: "agent", text: "Namaskar, Dr. Mehta Dental Clinic. Mi Asha boltey. Kashi madat karu?" },
      { speaker: "user", text: "Mala Saturday la cleaning sathi appointment havi aahe." },
      { speaker: "agent", text: "Nakkich! Saturday la 11:30 AM kinva 5:30 PM slot available aahe." },
      { speaker: "user", text: "5:30 chalel." },
      { speaker: "agent", text: "Done! Saturday 5:30 PM confirm. WhatsApp var confirmation pathavte. Dhanyawad!" },
    ],
  },
  {
    id: "call_9005",
    agentName: "Kabir — EMI Reminder",
    contactName: "Manoj Kumar",
    phone: "+91 90045 67xxx",
    direction: "outbound",
    status: "busy",
    durationSec: 0,
    costInr: 0.5,
    sentiment: "neutral",
    outcome: "Retry scheduled +4h",
    startedAt: "2026-07-06T16:05:00Z",
    transcript: [],
  },
  {
    id: "call_9006",
    agentName: "Riya — Sales Caller",
    contactName: "Deepika Nair",
    phone: "+91 98470 21xxx",
    direction: "outbound",
    status: "completed",
    durationSec: 176,
    costInr: 13.2,
    sentiment: "negative",
    outcome: "Not interested — budget",
    startedAt: "2026-07-06T14:30:00Z",
    transcript: [
      { speaker: "agent", text: "Hi Deepika! This is Riya from SharmaTech about your CRM enquiry." },
      { speaker: "user", text: "Oh yes, but honestly your pricing seems high for us right now." },
      { speaker: "agent", text: "I understand. May I ask what budget you had in mind? We do have a Starter plan too." },
      { speaker: "user", text: "We can't spend more than ₹2,000 a month currently." },
      { speaker: "agent", text: "Got it — I'll note that and share a link to our free tier. Thank you for your time, Deepika!" },
    ],
  },
];

export const seedCampaigns: Campaign[] = [
  {
    id: "cmp_01",
    name: "July Demo Follow-ups",
    agentName: "Riya — Sales Caller",
    status: "running",
    totalContacts: 1200,
    called: 745,
    connected: 512,
    converted: 138,
    scheduledFor: "2026-07-07T09:00:00Z",
    callWindow: "10 AM – 6 PM",
  },
  {
    id: "cmp_02",
    name: "EMI Due — 2nd Week July",
    agentName: "Kabir — EMI Reminder",
    status: "running",
    totalContacts: 3400,
    called: 2210,
    connected: 1688,
    converted: 1204,
    scheduledFor: "2026-07-06T08:30:00Z",
    callWindow: "9 AM – 7 PM",
  },
  {
    id: "cmp_03",
    name: "Dental Check-up Recall",
    agentName: "Asha — Clinic Receptionist",
    status: "scheduled",
    totalContacts: 480,
    called: 0,
    connected: 0,
    converted: 0,
    scheduledFor: "2026-07-10T10:00:00Z",
    callWindow: "11 AM – 5 PM",
  },
  {
    id: "cmp_04",
    name: "June NPS Survey",
    agentName: "Riya — Sales Caller",
    status: "completed",
    totalContacts: 900,
    called: 900,
    connected: 641,
    converted: 519,
    scheduledFor: "2026-06-28T10:00:00Z",
    callWindow: "10 AM – 6 PM",
  },
];

export const seedContacts: Contact[] = [
  { id: "ct_01", name: "Rahul Verma", phone: "+91 98201 44xxx", city: "Mumbai", tags: ["hot-lead", "crm"], lastCalled: "2026-07-07T10:42:00Z", dnd: false },
  { id: "ct_02", name: "Sunita Devi", phone: "+91 91556 78xxx", city: "Patna", tags: ["emi-due"], lastCalled: "2026-07-07T09:15:00Z", dnd: false },
  { id: "ct_03", name: "Farhan Sheikh", phone: "+91 99304 12xxx", city: "Mumbai", tags: ["new-lead"], lastCalled: "2026-07-07T08:58:00Z", dnd: false },
  { id: "ct_04", name: "Pooja Kulkarni", phone: "+91 98600 33xxx", city: "Pune", tags: ["patient"], lastCalled: "2026-07-06T18:20:00Z", dnd: false },
  { id: "ct_05", name: "Manoj Kumar", phone: "+91 90045 67xxx", city: "Lucknow", tags: ["emi-due"], lastCalled: "2026-07-06T16:05:00Z", dnd: false },
  { id: "ct_06", name: "Deepika Nair", phone: "+91 98470 21xxx", city: "Kochi", tags: ["cold"], lastCalled: "2026-07-06T14:30:00Z", dnd: false },
  { id: "ct_07", name: "Amitabh Joshi", phone: "+91 98110 90xxx", city: "Delhi", tags: ["hot-lead"], lastCalled: "2026-07-05T12:10:00Z", dnd: true },
  { id: "ct_08", name: "Lakshmi Raman", phone: "+91 94440 56xxx", city: "Chennai", tags: ["patient"], lastCalled: "2026-07-04T11:00:00Z", dnd: false },
];

export const seedNumbers: PhoneNumber[] = [
  { id: "num_01", number: "+91 22 4890 12xx", type: "virtual", provider: "Exotel", city: "Mumbai", assignedAgent: "Riya — Sales Caller", monthlyRentInr: 499, status: "active" },
  { id: "num_02", number: "+91 80 6912 88xx", type: "virtual", provider: "Plivo", city: "Bengaluru", assignedAgent: "Kabir — EMI Reminder", monthlyRentInr: 499, status: "active" },
  { id: "num_03", number: "1800 209 77xx", type: "toll-free", provider: "Tata Tele", city: "Pan-India", assignedAgent: "Asha — Clinic Receptionist", monthlyRentInr: 1299, status: "active" },
  { id: "num_04", number: "+91 20 7128 45xx", type: "virtual", provider: "Exotel", city: "Pune", assignedAgent: "—", monthlyRentInr: 499, status: "pending" },
];

export const seedTransactions: Transaction[] = [
  { id: "tx_101", date: "2026-07-05", description: "Wallet recharge (UPI — Razorpay)", type: "recharge", amountInr: 10000, status: "success" },
  { id: "tx_102", date: "2026-07-06", description: "Call usage — 312 minutes", type: "usage", amountInr: -1404, status: "success" },
  { id: "tx_103", date: "2026-07-01", description: "Number rental — July (3 numbers)", type: "rental", amountInr: -2297, status: "success" },
  { id: "tx_104", date: "2026-06-28", description: "Wallet recharge (Netbanking)", type: "recharge", amountInr: 25000, status: "success" },
  { id: "tx_105", date: "2026-06-25", description: "Failed call refund", type: "refund", amountInr: 86, status: "success" },
];

// ---- Admin data ----

export const seedClients: ClientAccount[] = [
  { id: "cl_01", company: "SharmaTech Solutions", owner: "Nikhil Sharma", email: "nikhil@sharmatech.in", phone: "+91 98201 11xxx", city: "Mumbai", plan: "Growth", status: "active", walletInr: 31299, agents: 3, minutesThisMonth: 1840, mrrInr: 7999, joinedAt: "2026-03-02" },
  { id: "cl_02", company: "FinServe NBFC", owner: "Ritu Malhotra", email: "ritu@finserve.in", phone: "+91 98110 22xxx", city: "Delhi", plan: "Scale", status: "active", walletInr: 118450, agents: 8, minutesThisMonth: 6920, mrrInr: 24999, joinedAt: "2026-01-15" },
  { id: "cl_03", company: "Dr. Mehta Dental Clinic", owner: "Dr. Anish Mehta", email: "anish@mehtadental.in", phone: "+91 98600 33xxx", city: "Pune", plan: "Starter", status: "active", walletInr: 4120, agents: 1, minutesThisMonth: 380, mrrInr: 2499, joinedAt: "2026-05-20" },
  { id: "cl_04", company: "Kanchi Silks", owner: "Lakshmi Subramanian", email: "lakshmi@kanchisilks.com", phone: "+91 94440 44xxx", city: "Chennai", plan: "Growth", status: "trial", walletInr: 500, agents: 2, minutesThisMonth: 112, mrrInr: 0, joinedAt: "2026-06-29" },
  { id: "cl_05", company: "UrbanNest Realty", owner: "Karan Oberoi", email: "karan@urbannest.in", phone: "+91 99870 55xxx", city: "Gurugram", plan: "Growth", status: "active", walletInr: 22750, agents: 5, minutesThisMonth: 2410, mrrInr: 7999, joinedAt: "2026-02-11" },
  { id: "cl_06", company: "SwiftCabs", owner: "Imran Qureshi", email: "imran@swiftcabs.in", phone: "+91 90000 66xxx", city: "Hyderabad", plan: "Starter", status: "suspended", walletInr: -240, agents: 1, minutesThisMonth: 0, mrrInr: 2499, joinedAt: "2026-04-08" },
  { id: "cl_07", company: "Ayurveda Wellness Co", owner: "Shreya Pillai", email: "shreya@ayurwell.in", phone: "+91 98470 77xxx", city: "Kochi", plan: "Enterprise", status: "active", walletInr: 402100, agents: 14, minutesThisMonth: 15230, mrrInr: 62000, joinedAt: "2025-11-30" },
];

export const seedPlans: Plan[] = [
  { id: "pl_01", name: "Starter", priceInr: 2499, includedMinutes: 500, overagePerMinInr: 5.5, maxAgents: 2, concurrency: 5, features: ["Hindi + English", "Recordings & transcripts", "Email support"], activeClients: 46 },
  { id: "pl_02", name: "Growth", priceInr: 7999, includedMinutes: 2000, overagePerMinInr: 4.5, maxAgents: 10, concurrency: 25, features: ["12 Indian languages", "Campaigns", "WhatsApp follow-ups", "Webhooks & CRM"], activeClients: 89 },
  { id: "pl_03", name: "Scale", priceInr: 24999, includedMinutes: 8000, overagePerMinInr: 3.5, maxAgents: 50, concurrency: 100, features: ["Custom voices", "SLA 99.9%", "Dedicated manager"], activeClients: 27 },
  { id: "pl_04", name: "Enterprise", priceInr: 62000, includedMinutes: 25000, overagePerMinInr: 2.8, maxAgents: 999, concurrency: 500, features: ["On-prem telephony", "Custom SIP trunks", "Security review"], activeClients: 6 },
];

export const seedProviders: ProviderConfig[] = [
  { id: "pv_01", name: "Exotel", category: "telephony", status: "connected", usageShare: 52, costNote: "₹0.35/min outbound" },
  { id: "pv_02", name: "Plivo", category: "telephony", status: "connected", usageShare: 31, costNote: "₹0.32/min outbound" },
  { id: "pv_03", name: "Twilio", category: "telephony", status: "degraded", usageShare: 17, costNote: "$0.014/min outbound" },
  { id: "pv_04", name: "Sarvam AI", category: "tts", status: "connected", usageShare: 44, costNote: "Indic TTS — ₹0.9/min" },
  { id: "pv_05", name: "ElevenLabs", category: "tts", status: "connected", usageShare: 38, costNote: "Premium voices — $0.08/min" },
  { id: "pv_06", name: "Deepgram", category: "stt", status: "connected", usageShare: 71, costNote: "Nova-3 — $0.0043/min" },
  { id: "pv_07", name: "Sarvam Saarika", category: "stt", status: "connected", usageShare: 29, costNote: "Indic STT — ₹0.5/min" },
  { id: "pv_08", name: "Anthropic Claude", category: "llm", status: "connected", usageShare: 78, costNote: "Sonnet 5 + Haiku 4.5" },
  { id: "pv_09", name: "OpenAI", category: "llm", status: "connected", usageShare: 22, costNote: "GPT-4o mini" },
];

export const seedTickets: SupportTicket[] = [
  { id: "tk_501", subject: "Calls dropping after 3 minutes on Exotel numbers", client: "FinServe NBFC", priority: "urgent", status: "in-progress", createdAt: "2026-07-06T14:00:00Z", lastUpdate: "2026-07-07T09:30:00Z" },
  { id: "tk_502", subject: "Need Tamil voice with slower speaking rate", client: "Kanchi Silks", priority: "medium", status: "open", createdAt: "2026-07-06T11:20:00Z", lastUpdate: "2026-07-06T11:20:00Z" },
  { id: "tk_503", subject: "GST invoice for June not generated", client: "UrbanNest Realty", priority: "high", status: "open", createdAt: "2026-07-05T16:45:00Z", lastUpdate: "2026-07-06T10:00:00Z" },
  { id: "tk_504", subject: "How to upload DND-scrubbed contact list?", client: "Dr. Mehta Dental Clinic", priority: "low", status: "resolved", createdAt: "2026-07-03T09:10:00Z", lastUpdate: "2026-07-04T12:30:00Z" },
];

// Chart data
export const callVolumeWeekly = [
  { day: "Mon", calls: 412, connected: 298 },
  { day: "Tue", calls: 488, connected: 356 },
  { day: "Wed", calls: 530, connected: 401 },
  { day: "Thu", calls: 465, connected: 340 },
  { day: "Fri", calls: 602, connected: 459 },
  { day: "Sat", calls: 380, connected: 291 },
  { day: "Sun", calls: 145, connected: 98 },
];

export const minutesByLanguage = [
  { language: "Hindi", minutes: 4820 },
  { language: "Hinglish", minutes: 3140 },
  { language: "English", minutes: 2260 },
  { language: "Marathi", minutes: 980 },
  { language: "Tamil", minutes: 745 },
  { language: "Telugu", minutes: 512 },
  { language: "Others", minutes: 638 },
];

export const adminRevenueMonthly = [
  { month: "Feb", mrr: 412000, minutes: 84000 },
  { month: "Mar", mrr: 538000, minutes: 109000 },
  { month: "Apr", mrr: 671000, minutes: 141000 },
  { month: "May", mrr: 802000, minutes: 176000 },
  { month: "Jun", mrr: 941000, minutes: 214000 },
  { month: "Jul", mrr: 1024000, minutes: 236000 },
];

export const adminSignupsWeekly = [
  { week: "W1", signups: 14, churned: 2 },
  { week: "W2", signups: 19, churned: 1 },
  { week: "W3", signups: 23, churned: 3 },
  { week: "W4", signups: 31, churned: 2 },
];
