import type { Metadata } from "next";
import Link from "next/link";
import { LegalShell, Section, List } from "@/components/legal/LegalPage";
import { LEGAL } from "@/lib/legal";

export const metadata: Metadata = {
  title: `Terms of Service · ${LEGAL.productName}`,
  description: `The terms under which ${LEGAL.productName} may be used.`,
};

export default function TermsPage() {
  return (
    <LegalShell
      title="Terms of Service"
      intro={`The agreement between you and ${LEGAL.legalEntity} for the use of ${LEGAL.productName}. By creating an account you accept these terms.`}
    >
      <Section title="What the service is">
        <p>
          {LEGAL.productName} connects to <strong>your own</strong> WhatsApp Business Account
          through Meta&apos;s WhatsApp Cloud API and automates replies, campaigns and workflows
          on it. We are not a Business Solution Provider, we do not resell WhatsApp messaging,
          and we do not mark up Meta&apos;s conversation charges — you are billed for messaging
          by Meta directly, and by us only for the software.
        </p>
      </Section>

      <Section title="Your account">
        <p>
          You are responsible for what happens under your account, including anything your team
          members do. Keep your password and API keys secret; tell us promptly if you think
          either has been exposed. You must be old enough to enter a contract where you live,
          and you must have authority to bind the business you are signing up.
        </p>
      </Section>

      <Section title="Meta's rules apply too">
        <p>
          Because messages go through WhatsApp, you must also comply with{" "}
          <a href="https://business.whatsapp.com/policy" target="_blank" rel="noopener noreferrer">
            the WhatsApp Business Messaging Policy
          </a>{" "}
          and the WhatsApp Business Terms. Those are Meta&apos;s rules, not ours, and Meta
          enforces them — they can restrict or ban your number regardless of anything we do. In
          particular:
        </p>
        <List
          items={[
            "Message people only where you have their opt-in. Buying phone number lists and messaging them is the fastest way to lose your number.",
            "Give people a clear way to opt out, and honour it.",
            "Outside the 24-hour customer service window, you may only send approved template messages.",
            "Do not use WhatsApp for the categories Meta prohibits.",
          ]}
        />
      </Section>

      <Section title="Acceptable use">
        <p>You agree not to use {LEGAL.productName} to:</p>
        <List
          items={[
            "Send spam, bulk unsolicited messages, or anything you do not have consent to send.",
            "Impersonate another person, business or brand.",
            "Distribute malware, run phishing, or attempt to obtain credentials or payment details under false pretences.",
            "Harass, threaten or abuse anyone.",
            "Break the law in your jurisdiction or your recipients'.",
            "Probe, scrape, overload or reverse-engineer the service, or circumvent its tenant isolation or rate limits.",
            "Resell or white-label the service without a written agreement with us.",
          ]}
        />
        <p>
          We may suspend an account that is doing any of these, and where the harm is ongoing
          we may do so without notice.
        </p>
      </Section>

      <Section title="Your data and your customers' data">
        <p>
          Your data stays yours. We do not sell it, and we do not use your customers&apos;
          messages to train AI models. You grant us only the licence needed to run the service
          for you — to store, process and transmit that data on your instruction.
        </p>
        <p>
          You are the controller of your contacts&apos; personal data. That means you are
          responsible for having a lawful basis to message them and for answering their privacy
          requests. See the <Link href="/privacy">Privacy Policy</Link> for the full picture.
        </p>
      </Section>

      <Section title="AI-generated replies">
        <p>
          If you enable an AI Assistant, replies are generated by a language model. Models can
          be wrong. <strong>You are responsible for what your assistant says to your
          customers</strong> — review its instructions, set handoff keywords so a human takes
          over when it matters, and do not use it unsupervised for medical, legal, financial or
          safety-critical advice.
        </p>
        <p>
          Every automated reply is recorded in the bot activity log so you can audit what was
          sent and why.
        </p>
      </Section>

      <Section title="Billing">
        <p>
          Paid plans are billed in advance for the period shown at checkout. Fees are
          non-refundable except where required by law or where we have clearly failed to
          deliver. We will give notice before a price change takes effect on your account. If
          payment fails we may suspend the service after notifying you.
        </p>
        <p>
          Meta bills you separately for WhatsApp conversations. That is between you and Meta.
        </p>
      </Section>

      <Section title="Availability">
        <p>
          We work to keep the service running but do not promise uninterrupted availability.
          Parts of it depend on Meta, and an outage or policy change on their side can stop
          messages flowing regardless of what we do.
        </p>
      </Section>

      <Section title="Liability">
        <p>
          The service is provided &quot;as is&quot;. To the maximum extent the law allows, we
          exclude implied warranties, and we are not liable for lost profits, lost data, lost
          business, or indirect or consequential loss. Our total liability in any 12-month
          period is limited to the fees you paid us in that period.
        </p>
        <p>Nothing here excludes liability that cannot lawfully be excluded.</p>
      </Section>

      <Section title="Ending it">
        <p>
          You can stop using the service and request deletion at any time — see{" "}
          <Link href="/data-deletion">data deletion</Link>. We may terminate for a material
          breach of these terms, ordinarily after telling you what the problem is and giving
          you a chance to fix it.
        </p>
      </Section>

      <Section title="Changes and governing law">
        <p>
          We may update these terms; material changes will be emailed to account owners before
          taking effect. These terms are governed by the laws of {LEGAL.jurisdiction}.
        </p>
        <p>
          Questions: <a href={`mailto:${LEGAL.contactEmail}`}>{LEGAL.contactEmail}</a>.
        </p>
      </Section>
    </LegalShell>
  );
}
